"""Create tables

Revision ID: 20eef6af4925
Revises: 
Create Date: 2024-07-03 12:18:56.078992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20eef6af4925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primary_immunization_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('patient_update_date', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('the_age', sa.String(), nullable=True),
    sa.Column('age_y', sa.Integer(), nullable=True),
    sa.Column('age_m', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deceased', sa.Boolean(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('multiple_birth', sa.Boolean(), nullable=True),
    sa.Column('pat_relation', sa.String(), nullable=True),
    sa.Column('pat_relation_name', sa.String(), nullable=True),
    sa.Column('pat_relation_tel', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('subcounty', sa.String(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('facility_code', sa.String(), nullable=True),
    sa.Column('the_vaccine_seq', sa.Integer(), nullable=True),
    sa.Column('vaccine_code', sa.String(), nullable=True),
    sa.Column('vaccine_name', sa.String(), nullable=True),
    sa.Column('vaccine_category', sa.String(), nullable=True),
    sa.Column('the_dose', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('occ_date', sa.String(), nullable=True),
    sa.Column('days_from_due', sa.Integer(), nullable=True),
    sa.Column('faci_outr', sa.String(), nullable=True),
    sa.Column('imm_status', sa.String(), nullable=True),
    sa.Column('imm_status_defaulter', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('primary_immunization_dataset')
    # ### end Alembic commands ###
