"""empty message

Revision ID: 6c7d775fe3b3
Revises: 
Create Date: 2024-10-25 09:42:57.100751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c7d775fe3b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primary_immunization_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('family_name', sa.String(length=100), nullable=True),
    sa.Column('given_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deceased', sa.Boolean(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('is_multiple_birth', sa.Boolean(), nullable=True),
    sa.Column('phone_primary', sa.String(length=50), nullable=True),
    sa.Column('phone_secondary', sa.String(length=50), nullable=True),
    sa.Column('contact_preference', sa.String(length=50), nullable=True),
    sa.Column('guardian_relationship', sa.String(length=50), nullable=True),
    sa.Column('guardian_name', sa.String(length=100), nullable=True),
    sa.Column('guardian_phone', sa.String(length=50), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('subcounty', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('facility_name', sa.String(length=200), nullable=True),
    sa.Column('facility_code', sa.String(length=50), nullable=True),
    sa.Column('vaccine_sequence', sa.Integer(), nullable=True),
    sa.Column('vaccine_code', sa.String(length=50), nullable=True),
    sa.Column('vaccine_name', sa.String(length=100), nullable=True),
    sa.Column('vaccine_category', sa.String(length=50), nullable=True),
    sa.Column('dose_number', sa.Integer(), nullable=True),
    sa.Column('dose_description', sa.String(length=200), nullable=True),
    sa.Column('series_name', sa.String(length=100), nullable=True),
    sa.Column('schedule_due_date', sa.Date(), nullable=True),
    sa.Column('administered_date', sa.Date(), nullable=True),
    sa.Column('days_from_due_date', sa.Integer(), nullable=True),
    sa.Column('next_dose_due_date', sa.Date(), nullable=True),
    sa.Column('administration_location', sa.String(length=200), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('administered_by', sa.String(length=100), nullable=True),
    sa.Column('immunization_status', sa.String(length=50), nullable=True),
    sa.Column('is_defaulter', sa.Boolean(), nullable=True),
    sa.Column('defaulter_days', sa.Integer(), nullable=True),
    sa.Column('target_disease', sa.String(length=200), nullable=True),
    sa.Column('disease_category', sa.String(length=100), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('record_updated_at', sa.DateTime(), nullable=True),
    sa.Column('patient_last_updated', sa.DateTime(), nullable=True),
    sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adverse_reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('primary_immunization_dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_facility_code'), ['facility_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_facility_name'), ['facility_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_immunization_status'), ['immunization_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_is_defaulter'), ['is_defaulter'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_national_id'), ['national_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_schedule_due_date'), ['schedule_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_subcounty'), ['subcounty'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_vaccine_code'), ['vaccine_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('primary_immunization_dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_vaccine_code'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_subcounty'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_schedule_due_date'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_patient_id'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_national_id'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_is_defaulter'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_immunization_status'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_facility_name'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_facility_code'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_county'))

    op.drop_table('primary_immunization_dataset')
    # ### end Alembic commands ###
