"""empty message

Revision ID: 93ec9ad26356
Revises: 20eef6af4925
Create Date: 2024-10-17 15:46:09.483695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ec9ad26356'
down_revision = '20eef6af4925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('primary_immunization_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pat_contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('batch_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_disease', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('primary_immunization_dataset', schema=None) as batch_op:
        batch_op.drop_column('target_disease')
        batch_op.drop_column('batch_number')
        batch_op.drop_column('pat_contact')

    # ### end Alembic commands ###
