"""empty message

Revision ID: a3c55494aa47
Revises: 6c7d775fe3b3
Create Date: 2024-10-25 12:07:36.172779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3c55494aa47'
down_revision = '6c7d775fe3b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('primary_immunization_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('schedule_due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('administered_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('ix_primary_immunization_dataset_facility_code')
        batch_op.drop_index('ix_primary_immunization_dataset_facility_name')
        batch_op.drop_index('ix_primary_immunization_dataset_national_id')
        batch_op.drop_index('ix_primary_immunization_dataset_schedule_due_date')
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_primary_immunization_dataset_document_type'), ['document_type'], unique=False)
        batch_op.drop_column('administered_by')
        batch_op.drop_column('next_dose_due_date')
        batch_op.drop_column('adverse_reactions')
        batch_op.drop_column('created_by')
        batch_op.drop_column('clinical_notes')
        batch_op.drop_column('dose_description')
        batch_op.drop_column('contact_preference')
        batch_op.drop_column('national_id')
        batch_op.drop_column('contraindications')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('vaccine_sequence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('primary_immunization_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccine_sequence', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('national_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_preference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dose_description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clinical_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adverse_reactions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_dose_due_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('administered_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_document_type'))
        batch_op.drop_index(batch_op.f('ix_primary_immunization_dataset_document_id'))
        batch_op.create_index('ix_primary_immunization_dataset_schedule_due_date', ['schedule_due_date'], unique=False)
        batch_op.create_index('ix_primary_immunization_dataset_national_id', ['national_id'], unique=False)
        batch_op.create_index('ix_primary_immunization_dataset_facility_name', ['facility_name'], unique=False)
        batch_op.create_index('ix_primary_immunization_dataset_facility_code', ['facility_code'], unique=False)
        batch_op.alter_column('administered_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('schedule_due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('document_type')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###
